### ISSUE TITLE
JavaMail 1.6.2 breaks mock-javamail

### ISSUE THREAD

**Issue by robtimus** [jenkinsci/lib-mock-javamail#2]
JavaMail 1.6.2 added support for the ServiceLoader mechanism; see https://javaee.github.io/javamail/#Latest_News. However, this is used before the javamail.providers mechanism:

    private Provider getProviderByProtocol(String protocol) {
        // first, try our local list of providers
        Provider p = providersByProtocol.get(protocol);
        if (p != null)
            return p;

        // now, try services
        ServiceLoader<Provider> loader = ServiceLoader.load(Provider.class);
        for (Provider pp : loader) {
            if (protocol.equals(pp.getProtocol()))
                return pp;
        }

        // finally, if we haven't loaded our config, load it and try again
        if (!loadedProviders) {
            loadProviders(true);
            p = providersByProtocol.get(protocol);
        }
        return p;
    }

As a result, the real SMTP provider is used and not the mock SMTP provider. This basically makes the mock useless.

A quick solution is to downgrade JavaMail (if possible), or perhaps to provide a custom protocol that wraps class MockTransport:

    public class MockSMTPProvider extends Provider {

        public MockSMTPProvider() {
            super(Type.TRANSPORT, "smtp", MockTransport.class.getName(), "kohsuke", "1.9");
        }
    }

In addition, you need file `META-INF/services/javax.mail.Provider` that contains one line, with the fully qualifier class name of the provider.

Finally, you'll need to do the same for MockStore.

**Comment by robtimus** [comment]
I noticed that this is a duplicate of https://github.com/kohsuke/mock-javamail/pull/1.

**Comment by basil** [comment]
Fixed in #3.
