### ISSUE TITLE
Rename META-INF/services/javax.mail.Provider to META-INF/services/jakarta.mail.Provider

### ISSUE THREAD

**Issue by jensppi** [jenkinsci/lib-mock-javamail#48]
### What feature do you want to see added?

I have to rename META-INF/services/**javax**.mail.Provider to META-INF/services/**jakarta**.mail.Provider to have your mock implementations being the first in the provider list in jakarta.mail.Session#loadProviders .

We used mock-javamail 1.9 for years with javax.mail. To continue testing with jakarta.mail, we had to perform the mentioned file renaming to use mock-javamail 2.0.

Great work! Many thanks. Greetings from Kiel, Germany
Jens

**Comment by basil** [comment]
Are you interested in opening a pull request?
